# -*- coding: utf-8 -*-
"""Select_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RiTy6m6XkFJ7X_8OL9hLZpkbPeDoJM1p
"""

import json
import pandas as pd

json_path = "dev.json"

with open(json_path, "r", encoding="utf-8") as f:
    data = json.load(f)

required_ids = {
    0, 3, 6, 7, 8, 9, 12, 13, 14, 20, 21, 23,
    28, 31, 33, 34, 35, 36, 37, 38, 39, 40,
    43, 44, 45, 46, 47
}

filtered = [
    {
        "question_id": r.get("question_id"),
        "question": r.get("question"),
        "SQL": r.get("SQL"),
        "difficulty": r.get("difficulty")
    }
    for r in data if r.get("question_id") in required_ids
]

df = pd.DataFrame(filtered)
df.to_excel("filtered_questions.xlsx", index=False)